package model;

import java.util.Date;

/**
 * Represents a workout plan generated by the AI.
 */
public class WorkoutPlan {
    private String content;
    private Date created;
    private String goals;
    private String level;
    private String time;
    private String fav;
    private String special;

    public WorkoutPlan(String content, String goals, String level, 
                      String time, String fav, String special) {
        this.content = content;
        this.created = new Date();
        this.goals = goals;
        this.level = level;
        this.time = time;
        this.fav = fav;
        this.special = special;
    }

    public String getContent() { return content; }
    public Date getCreated() { return created; }
    public String getGoals() { return goals; }
    public String getLevel() { return level; }
    public String getTime() { return time; }
    public String getFav() { return fav; }
    public String getSpecial() { return special; }
}